# Generated by Django 3.0.8 on 2020-07-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('agglomerative', 'Agglomerative'), ('k-means', 'K-means'), ('spectral', 'Spectral')], default='k-means', max_length=13)),
                ('n_clusters', models.IntegerField()),
                ('min_length', models.IntegerField()),
                ('max_length', models.IntegerField()),
            ],
        ),
    ]
